# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [9]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

print('3d array:\n', arr)
print('\n1st layer:\n', arr[0])
print('\n2nd row of 2nd layer:\n', arr[1,1])
print('\nElement 11:\n', arr[1,1,1])

3d array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1st layer:
 [[1 2 3]
 [4 5 6]]

2nd row of 2nd layer:
 [10 11 12]

Element 11:
 11


# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [11]:
print('\nReverse the order of layers:\n', arr[::-1])


Reverse the order of layers:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [12]:
print('\nReverse every row inside every layer:\n', arr[::-1, ::-1])


Reverse every row inside every layer:
 [[[10 11 12]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 1  2  3]]]


# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [13]:
print('\nCompletely reverse the entire 3D array:\n', arr[::-1, ::-1, ::-1])


Completely reverse the entire 3D array:
 [[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]


# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [15]:
student = {'Roll No' : 101, 'Name' : 'Alice', 'Age' : 20, 'Department' : 'AI & DS', 'CGPA' : 8.9}
print(student)

{'Roll No': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 8.9}


In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [16]:
student['CGPA'] = 9.2
student['City'] = 'Chennai'
print(student)

{'Roll No': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 9.2, 'City': 'Chennai'}


In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [25]:
print('All Keys:')
for key in student:
    print(key)
print('\nAll Values:')
for value in student.values():
    print(value)
print('\nAll key-value pairs:')
for key, value in student.items():
    print(f"{key}, {value}")

All Keys:
Roll No
Name
Age
Department
CGPA
City

All Values:
101
Alice
20
AI & DS
9.2
Chennai

All key-value pairs:
Roll No, 101
Name, Alice
Age, 20
Department, AI & DS
CGPA, 9.2
City, Chennai


In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [40]:
students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}
print('\nName of student 2:', students["Student2"]["Name"])
print('\nAge of student 3:', students["Student3"]["Age"])
print('\nAll student names:')
for student_id, info in students.items():
    print(info["Name"])


Name of student 2: Alice

Age of student 3: 20

All student names:
John
Alice
David


In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [45]:
products = {
    "Product1" : {
        "Name" : "Laptop",
        "Price" : 500,
        "Quantity" : 1,
    },
    "Product2" : {
        "Name" : "Mouse",
        "Price" : 10,
        "Quantity" : 2,
    },
    "Product3" : {
        "Name" : "Keyboard",
        "Price" : 100,
        "Quantity" : 3,
    },
    "Product4" : {
        "Name" : "Monitor",
        "Price" : 200,
        "Quantity" : 4,
    },
    "Product5" : {
        "Name" : "Printer",
        "Price" : 50,
        "Quantity" : 5,
    }
}
print (products)
highest_price_product = max(products.values(), key=lambda x: x["Price"])
print ("\nHighest Price Product:", highest_price_product)
total_value = sum(item["Price"] * item["Quantity"] for item in products.values())
print ("\nTotal Inventory Value:", total_value)

{'Product1': {'Name': 'Laptop', 'Price': 500, 'Quantity': 1}, 'Product2': {'Name': 'Mouse', 'Price': 10, 'Quantity': 2}, 'Product3': {'Name': 'Keyboard', 'Price': 100, 'Quantity': 3}, 'Product4': {'Name': 'Monitor', 'Price': 200, 'Quantity': 4}, 'Product5': {'Name': 'Printer', 'Price': 50, 'Quantity': 5}}

Highest Price Product: {'Name': 'Laptop', 'Price': 500, 'Quantity': 1}

Total Inventory Value: 1870


In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [54]:
students = {
    "Student1": {
        "Name": "Alice",
        "Marks": 85
    },
    "Student2": {
        "Name": "Bob",
        "Marks": 92
    },
    "Student3": {
        "Name": "Charlie",
        "Marks": 78
    },
    "Student4": {
        "Name": "David",
        "Marks": 88
    },
    "Student5": {
        "Name": "Emma",
        "Marks": 95
    }
}
student_highest_marks = max(students.values(), key=lambda x: x["Marks"])
print ("\nStudent with the highest marks:", student_highest_marks)

student_lowest_marks = min(students.values(), key=lambda x: x["Marks"])
print ("\nStudent with the lowest marks:", student_lowest_marks)

average_marks = sum(student["Marks"] for student in students.values()) / len (students)
print ("\nAverage marks:", average_marks)

students_above_85 = ([info["Name"] for name, info in students.items() if info['Marks'] > 85])
print ("\nStudents who scored more than 85:", students_above_85)


Student with the highest marks: {'Name': 'Emma', 'Marks': 95}

Student with the lowest marks: {'Name': 'Charlie', 'Marks': 78}

Average marks: 87.6

Students who scored more than 85: ['Bob', 'David', 'Emma']
